/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-11-11 03:04:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Project/cho_hyun_wook/PJT_03/ProjectC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/reservation/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604807698003L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"네이버 예약, 네이버 예약이 연동된 곳 어디서나 바로 예약하고, 네이버 예약 홈(나의예약)에서 모두 관리할 수 있습니다.\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no\">\r\n");
      out.write("<title>네이버 예약</title>\r\n");
      out.write("<link href=\"static/css/reservation.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"static/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<header class=\"header_tit\">\r\n");
      out.write("\t\t\t\t<h1 class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"https://m.naver.com/\" class=\"lnk_logo\" title=\"네이버\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"spr_bi ico_n_logo\">네이버</span>\r\n");
      out.write("\t\t\t\t\t</a> <a href=\"./myreservation.html\" class=\"lnk_logo\" title=\"예약\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"spr_bi ico_bk_logo\">예약</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<a href=\"./bookinglogin.html\" class=\"btn_my\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"viewReservation\" title=\"예약확인\">예약확인</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div class=\"event\">\r\n");
      out.write("\t\t\t<div class=\"section_visual\">\r\n");
      out.write("\t\t\t\t<div class=\"group_visual\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container_visual\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"prev_e\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"prev_inn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn_pre_e\" title=\"이전\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"spr_book_event spr_event_pre\">이전</i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nxt_e\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nxt_inn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn_nxt_e\" title=\"다음\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"spr_book_event spr_event_nxt\">다음</i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container_visual\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 슬라이딩기능: 이미지 (type = 'th')를 순차적으로 노출 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"visual_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--  <li><img class=\"img_promotion\" alt=\"test\" src=\"static/img/1_th_1.png\"></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"nxt_fix\" style=\"display: none;\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"section_event_tab\">\r\n");
      out.write("\t\t\t\t<ul class=\"event_tab_lst tab_lst_min\">\r\n");
      out.write("\t\t\t\t\t<li class=\"item\"><a class=\"anchor active\"> <span>전체리스트</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"section_event_lst\">\r\n");
      out.write("\t\t\t\t<p class=\"event_lst_txt\">\r\n");
      out.write("\t\t\t\t\t바로 예매 가능한 행사가 <span class=\"pink\">10개</span> 있습니다\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"wrap_event_box\">\r\n");
      out.write("\t\t\t\t\t<!-- [D] lst_event_box 가 2컬럼으로 좌우로 나뉨, 더보기를 클릭할때마다 좌우 ul에 li가 추가됨 -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"lst_event_box\">\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"lst_event_box\">\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!-- 더보기 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"more\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn\" id=\"button_more\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>더보기</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"gototop\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"lnk_top\"> <span class=\"lnk_top_text\">TOP</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t<p class=\"dsc_footer\">네이버(주)는 통신판매의 당사자가 아니며, 상품의정보, 거래조건, 이용 및\r\n");
      out.write("\t\t\t\t환불 등과 관련한 의무와 책임은 각 회원에게 있습니다.</p>\r\n");
      out.write("\t\t\t<span class=\"copyright\">© NAVER Corp.</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"rv-template\" id=\"promotionItem\">\r\n");
      out.write("    <li class=\"item\" style=\"background-image: url('static/{productImageUrl}'); width: 414px;\">\r\n");
      out.write("        <a href=\"#\"> <span class=\"img_btm_border\"></span> <span class=\"img_right_border\"></span> <span class=\"img_bg_gra\"></span>\r\n");
      out.write("            <div class=\"event_txt\">\r\n");
      out.write("                <h4 class=\"event_txt_tit\"></h4>\r\n");
      out.write("                <p class=\"event_txt_adr\"></p>\r\n");
      out.write("                <p class=\"event_txt_dsc\"></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"rv-template\" id=\"itemList\">\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("            <a href=\"detail.html?id={productId}\" class=\"item_book\">\r\n");
      out.write("                <div class=\"item_preview\">\r\n");
      out.write("                    <img alt=\"{productDescription}\" class=\"img_thumb\" src=\"static/{productImageUrl}\">\r\n");
      out.write("                    <span class=\"img_border\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"event_txt\">\r\n");
      out.write("                    <h4 class=\"event_txt_tit\"> <span>{productDescription}</span> <small class=\"sm\">{placeName}</small> </h4>\r\n");
      out.write("                    <p class=\"event_txt_dsc\">{productContent}</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/mainpage.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
